### ISSUE TITLE
jNode프레임워크와 비지니스 파일들을 서로로부터 독립시키고 싶습니다.

### ISSUE THREAD

**Issue by smn3786** [gurumdari/jnode#1]
제공하는 문서의 가이드를 참고해 아래와 같이 작업해 보았습니다.

![image](https://user-images.githubusercontent.com/54346337/70024525-b95c2180-15dd-11ea-82d6-72195c819c27.png)

**와 같이 리소스 경로를 구성하고 $jnode$.selector.js에서** 

![image](https://user-images.githubusercontent.com/54346337/70024546-d2fd6900-15dd-11ea-8c6e-b2832c3337d3.png)

**과 같이 설정하였습니다.**

이 경우 직접 작정하는 파일들은 jNode폴더로부터 독립되어 관리를 할 수 있지만 jNode의 controller또는 module을 사용할 수 없게 됩니다.

jNode폴더와 비지니스 코드들이 서로 독립된 공간을 가지고 있는것이 관리적인 측면에서 수월 할 것 같습니다.

**Comment by gurumdari** [comment]
jnode 디렉토리 안에는 설정 및 라이브러리들이 관리되는 디렉토리로 conf와 lib가 있고, template 파일(html, ejs, pug, ... 등)과 rendering 관련 파일(css, js, less, coffee, ... 등)이 관리되는 디렉토리로 template과 renderer가 있습니다.

template 파일(html, ejs, pug, ... 등)과 rendering 관련 파일(css, js, less, coffee, ... 등)이 주로 개발를 위한 비니지스 코드들이 사용되는 디렉토리이므로 이들만 따로 지정해서 독립시킬 수 있게 구현이 되어 있습니다. 그러나, template과 renderer 디렉토리 안에 Controller를 위한 CSS, Theme를 위한 CSS, 에러처리에 대한 EJS와 CSS가 같이 포함되어 있어서 독립시키기를 원하는 것으로 생각됩니다.

이부분은 상당히 고민이 되는 부분입니다. Jnode Framework을 개발하면서 최대한 노력한 부분이 바로 CSS, JavaScript, Template 등을 갭슐화하고 이에 대한 설정을 하는 별도의 API를 제공하는 방식을 사용하지 않을려고 한 점입니다. CSS, JavaScript, Template 자체를 직접 수정해서 원하는 UX를 만들 수 있게 구현하고자 노력했습니다. Controller나 Theme를 위한 CSS 등은 실제 적용 환경에 맞게 수정될 부분이라 생각되었기 때문에 Jnode Framework의 Core라기보다는 Customizing이 가능한 영역으로 생각했습니다. 에러처리에 대한 EJS와 CSS 파일도 같은 맥락으로 판단했기 때문에 독립된 디렉토리로 설정 시 같이 적용이 됩니다.
