### ISSUE TITLE
특정영역에서만 유효한 함수를 관리를 jNode가 자동으로 처리할 수 있다면

### ISSUE THREAD

**Issue by smn3786** [gurumdari/jnode#3]
![image](https://user-images.githubusercontent.com/54346337/70026605-874dbe00-15e3-11ea-9546-c28abaff36ec.png)

특정 영역에 한정된 함수를 
service 내 선언하여 window 객체에 이를 등록하고 unload시 직접 선언한 함수를 삭제함으로써
해당 함수의 라이프 사이클을 관리하도록 되어 있습니다.

![image](https://user-images.githubusercontent.com/54346337/70026480-448be600-15e3-11ea-8893-22e15e1c0d01.png)

간단한 아이디어로 addEventListener를 직접사용하지 않고 jNode에서 제공하는 이벤트 등록함수를 통해서 그 특정영역의 컨텐츠가 unload될 때 자동으로 제거를 해준다면 좀 더 깔끔한 코드작성과 사람이 할 수 있는 실수를 줄일 수 있지 않을까 생각합니다.

**Comment by gurumdari** [comment]
좋은 의견이지만 반영하기는 어려울 것 같습니다. unload시 등록된 객체나 함수 혹은 이벤트를 제거하는 방법이 다 다르기 때문입니다. delete로 제거해야 할 수도 있고, remveEventListener로 제거해야 할 수도 있고 기타 다른 방법이 필요할 수도 있기 때문입니다. unload 시 처리되어야 할 것을 unload function에 모아 놓는 것이나, 별도로 제공되는 api를 통해 service 함수에서 모아서 정의하는 것이나 크게 차이가 나지 않을 것 같기도 합니다.
